import {useEffect,useMemo,useState} from 'react'
import {Routes,Route,useNavigate,useParams} from 'react-router-dom'
import {DndContext,closestCenter,PointerSensor,useSensor,useSensors,DragEndEvent} from '@dnd-kit/core'
import {SortableContext,useSortable,verticalListSortingStrategy,arrayMove} from '@dnd-kit/sortable'
import {CSS} from '@dnd-kit/utilities'
import {Alert,AppBar,Avatar,Box,Button,Card,CardContent,Chip,CircularProgress,CssBaseline,Dialog,DialogActions,DialogContent,DialogTitle,Divider,Drawer,FormControl,IconButton,InputLabel,MenuItem,Select,Snackbar,Stack,Tab,Tabs,TextField,ThemeProvider,Tooltip,Typography,createTheme} from '@mui/material'
import {Add,ArrowBack,AutoAwesome,Cancel,CheckCircle,CloudUpload,ContentCopy,DarkMode,DeleteOutline,DragIndicator,Edit,Favorite,FavoriteBorder,FileDownload,FilterAlt,FolderOpen,GridView,LightMode,PlayArrow,RadioButtonUnchecked,Save,Search,TableChart} from '@mui/icons-material'
import {createPipeline,listPipelines,runPipeline,runToNode,savePipeline,api} from './api'
import type {Execution,Pipeline,PipelineNode,Preview,NodeType} from './types'

const catalog:{category:string;items:{type:NodeType;label:string;icon:string}[]}[]=[
 {category:'Column operations',items:[{type:'keep_columns',label:'Keep columns',icon:'⌗'},{type:'remove_columns',label:'Remove columns',icon:'⊖'},{type:'rename_columns',label:'Rename columns',icon:'Aa'},{type:'fill_null',label:'Fill nulls',icon:'∅'},{type:'case',label:'Change case',icon:'TT'},{type:'calculated',label:'Calculated column',icon:'ƒx'}]},
 {category:'Row operations',items:[{type:'filter',label:'Filter rows',icon:'≡'},{type:'sort',label:'Sort',icon:'⇅'},{type:'remove_duplicates',label:'Remove duplicates',icon:'≠'},{type:'top_n',label:'Keep top N',icon:'#'}]},
 {category:'Data operations',items:[{type:'aggregate',label:'Aggregate',icon:'Σ'}]},
 {category:'Quality',items:[{type:'validation',label:'Validation rule',icon:'✓'}]}
]
const labels=Object.fromEntries(catalog.flatMap(c=>c.items.map(i=>[i.type,i.label])))
const blank=():Partial<Pipeline>=>({name:'Untitled pipeline',description:'Build a trusted, reusable data flow',nodes:[],connections:[],tags:[]})
const nodeRunResults=new Map<string,{status:'success'|'failed';error?:string}>()

function Shell({children,dark,setDark}:{children:any;dark:boolean;setDark:(v:boolean)=>void}){
 return <><AppBar position="static" elevation={0} color="inherit"><Stack direction="row" alignItems="center" px={3} height={68} gap={1.5}><Box className="logo"><AutoAwesome fontSize="small"/></Box><Typography variant="h6" fontWeight={800}>DataFlow</Typography><Chip label="STUDIO" size="small" className="studio"/><Box flex={1}/><Tooltip title="Toggle theme"><IconButton onClick={()=>setDark(!dark)}>{dark?<LightMode/>:<DarkMode/>}</IconButton></Tooltip><Divider orientation="vertical" flexItem sx={{my:2}}/><Avatar sx={{width:34,height:34,bgcolor:'primary.main'}}>AS</Avatar></Stack></AppBar>{children}</>
}

function Dashboard(){
 const nav=useNavigate(),[items,setItems]=useState<Pipeline[]>([]),[loading,setLoading]=useState(true),[search,setSearch]=useState(''),[createOpen,setCreateOpen]=useState(false),[draft,setDraft]=useState(blank()),[snack,setSnack]=useState('')
 const load=()=>listPipelines().then(setItems).finally(()=>setLoading(false)); useEffect(()=>{void load()},[])
 const filtered=items.filter(p=>(p.name+p.description+p.tags.join(' ')).toLowerCase().includes(search.toLowerCase()))
 const create=async()=>{const p=await createPipeline(draft);setCreateOpen(false);nav(`/pipeline/${p.id}`)}
 const importPipeline=async(e:any)=>{
  const file=e.target.files?.[0]; e.target.value=''
  if(!file)return
  try{
   const data=JSON.parse(await file.text())
   const source=data.pipeline||data
   if(typeof source.name!=='string'||!Array.isArray(source.nodes))throw new Error('Invalid pipeline file')
   const created=await createPipeline({name:source.name,description:source.description||'',created_by:source.created_by||'You',tags:source.tags||[],favorite:false,nodes:source.nodes,connections:source.connections||[]})
   setSnack(`Imported “${created.name}”`); await load()
  }catch(error:any){setSnack(error?.message||'Could not import pipeline')}
 }
 const action=async(kind:string,p:Pipeline)=>{if(kind==='delete'&&confirm(`Delete “${p.name}”?`)){await api.delete(`/pipelines/${p.id}`);load()}if(kind==='duplicate'){await api.post(`/pipelines/${p.id}/duplicate`);load()}if(kind==='run'){await runPipeline(p.id);load()}}
 return <Box className="page"><Box className="hero"><Stack direction={{xs:'column',md:'row'}} justifyContent="space-between" gap={3}><Box><Typography variant="h3" fontWeight={800}>Your pipelines</Typography><Typography color="text.secondary" mt={1}>Design, validate, and transform data with confidence.</Typography></Box><Stack direction="row" alignItems="center" gap={1}><Button component="label" variant="outlined" startIcon={<CloudUpload/>}>Import<input hidden type="file" accept=".json,application/json" onChange={importPipeline}/></Button><Button variant="contained" startIcon={<Add/>} onClick={()=>setCreateOpen(true)}>New pipeline</Button></Stack></Stack>
 <Stack direction={{xs:'column',sm:'row'}} mt={4} gap={2}><TextField fullWidth size="small" placeholder="Search pipelines, descriptions, or tags…" value={search} onChange={e=>setSearch(e.target.value)} InputProps={{startAdornment:<Search sx={{mr:1,color:'text.secondary'}}/>}}/><Button variant="outlined" startIcon={<FilterAlt/>}>Filter</Button><Button variant="outlined" startIcon={<GridView/>}>Updated</Button></Stack></Box>
 {loading?<Box className="center"><CircularProgress/></Box>:filtered.length===0?<Box className="empty"><Box className="emptyIcon"><AutoAwesome/></Box><Typography variant="h5" fontWeight={700}>Turn raw data into answers</Typography><Typography color="text.secondary">Create your first pipeline and start shaping better data.</Typography><Button variant="contained" startIcon={<Add/>} onClick={()=>setCreateOpen(true)}>Create pipeline</Button></Box>:<Box className="cards">{filtered.map(p=><Card key={p.id} className="pipelineCard"><CardContent><Stack direction="row" justifyContent="space-between"><Box className="fileIcon"><TableChart/></Box><Stack direction="row"><Tooltip title={p.favorite?'Remove favorite':'Add favorite'}><IconButton onClick={()=>api.put(`/pipelines/${p.id}`,{favorite:!p.favorite}).then(load)}>{p.favorite?<Favorite color="error"/>:<FavoriteBorder/>}</IconButton></Tooltip><Tooltip title="Edit pipeline"><IconButton onClick={()=>nav(`/pipeline/${p.id}`)}><Edit/></IconButton></Tooltip></Stack></Stack><Typography variant="h6" mt={2} fontWeight={750}>{p.name}</Typography><Typography color="text.secondary" className="clamp">{p.description||'No description yet'}</Typography><Stack direction="row" gap={.7} mt={2}>{p.tags.slice(0,3).map(t=><Chip key={t} label={t} size="small"/>)}</Stack><Divider sx={{my:2}}/><Stack direction="row" justifyContent="space-between"><Typography variant="caption" color="text.secondary">{p.input_count} files · {p.step_count} steps</Typography><Chip size="small" label={p.last_status} color={p.last_status==='success'?'success':p.last_status==='failed'?'error':'default'}/></Stack><Typography variant="caption" color="text.secondary">Updated {new Date(p.updated_at).toLocaleDateString()}</Typography><Stack mt={2} direction="row" gap={1}><Button fullWidth variant="contained" startIcon={<FolderOpen/>} onClick={()=>nav(`/pipeline/${p.id}`)}>Open</Button><Tooltip title="Run"><IconButton onClick={()=>action('run',p)}><PlayArrow/></IconButton></Tooltip><Tooltip title="Duplicate"><IconButton onClick={()=>action('duplicate',p)}><ContentCopy/></IconButton></Tooltip><Tooltip title="Delete"><IconButton onClick={()=>action('delete',p)}><DeleteOutline/></IconButton></Tooltip></Stack></CardContent></Card>)}</Box>}
 <Dialog open={createOpen} onClose={()=>setCreateOpen(false)} fullWidth maxWidth="sm"><DialogTitle>Create a pipeline</DialogTitle><DialogContent><Stack gap={2} mt={1}><TextField label="Pipeline name" autoFocus value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/><TextField multiline rows={3} label="Description" value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/><TextField label="Tags (comma separated)" onChange={e=>setDraft({...draft,tags:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)})}/></Stack></DialogContent><DialogActions><Button onClick={()=>setCreateOpen(false)}>Cancel</Button><Button variant="contained" onClick={create}>Create & open</Button></DialogActions></Dialog><Snackbar open={!!snack} autoHideDuration={3000} onClose={()=>setSnack('')} message={snack}/></Box>
}

function SortableNode({node,index,selected,status,error,onSelect}:{node:PipelineNode;index:number;selected:boolean;status?:'success'|'failed';error?:string;onSelect:()=>void}){
 const {attributes,listeners,setNodeRef,transform,transition,isDragging}=useSortable({id:node.id})
 const latest=nodeRunResults.get(node.id); status=status||latest?.status; error=error||latest?.error
 return <Box ref={setNodeRef} style={{transform:CSS.Transform.toString(transform),transition,opacity:isDragging?.5:1}}><Card onClick={onSelect} className={`node ${selected?'selected':''}`}><Stack direction="row" alignItems="center" p={1.5} gap={1.5}><IconButton size="small" {...attributes} {...listeners}><DragIndicator/></IconButton><Box className={`nodeIcon ${node.type}`}>{node.type==='validation'?'✓':node.type==='input'?'↥':catalog.flatMap(x=>x.items).find(x=>x.type===node.type)?.icon}</Box><Box flex={1}><Typography fontWeight={700}>{node.name}</Typography><Typography variant="caption" color="text.secondary">{node.type==='input'?node.config.originalName:`Step ${index}`}</Typography></Box><Tooltip title={status==='success'?'Success':status==='failed'?`Failed${error?`: ${error}`:''}`:'Not run'}><Box className={`nodeStatus ${status||'not-run'}`}>{status==='success'?<CheckCircle color="success"/>:status==='failed'?<Cancel color="error"/>:<RadioButtonUnchecked color="disabled"/>}</Box></Tooltip><Chip label={node.type==='validation'?'CHECK':'STEP'} size="small"/></Stack></Card>{index>0&&<Box className="connector"/>}</Box>
}

function Properties({node,columns,onChange,onDelete}:{node?:PipelineNode;columns:string[];onChange:(n:PipelineNode)=>void;onDelete:()=>void}){
 if(!node)return <Box className="propertiesEmpty"><Edit/><Typography>Select a step to configure it</Typography></Box>
 const c=node.config,set=(key:string,value:any)=>onChange({...node,config:{...c,[key]:value}})
 return <Box p={2.5}><Stack direction="row" alignItems="center"><Box flex={1}><Typography variant="overline" color="primary">Properties</Typography><Typography variant="h6" fontWeight={750}>{node.name}</Typography></Box><IconButton color="error" onClick={onDelete}><DeleteOutline/></IconButton></Stack><Divider sx={{my:2}}/><Stack gap={2}><TextField size="small" label="Step name" value={node.name} onChange={e=>onChange({...node,name:e.target.value})}/>
 {node.type==='filter'&&<><ColumnSelect value={c.column} columns={columns} onChange={v=>set('column',v)}/><FormControl size="small"><InputLabel>Operator</InputLabel><Select label="Operator" value={c.operator||'equals'} onChange={e=>set('operator',e.target.value)}>{['equals','not_equals','contains','greater','less','is_null','not_null'].map(x=><MenuItem value={x}>{x.replace('_',' ')}</MenuItem>)}</Select></FormControl>{!['is_null','not_null'].includes(c.operator)&&<TextField size="small" label="Value" value={c.value||''} onChange={e=>set('value',e.target.value)}/>}</>}
 {node.type==='validation'&&<><ColumnSelect value={c.column} columns={columns} onChange={v=>set('column',v)}/><FormControl size="small"><InputLabel>Rule</InputLabel><Select label="Rule" value={c.rule||'null'} onChange={e=>set('rule',e.target.value)}>{['null','unique','regex','range','allowed'].map(x=><MenuItem value={x}>{x}</MenuItem>)}</Select></FormControl>{c.rule==='regex'&&<TextField size="small" label="Pattern" value={c.pattern||''} onChange={e=>set('pattern',e.target.value)}/>}<TextField size="small" label="Failure message" value={c.message||''} onChange={e=>set('message',e.target.value)}/></>}
 {['keep_columns','remove_columns','sort','remove_duplicates'].includes(node.type)&&<FormControl size="small"><InputLabel>Columns</InputLabel><Select multiple label="Columns" value={c.columns||[]} onChange={e=>set('columns',e.target.value)}>{columns.map(x=><MenuItem value={x}>{x}</MenuItem>)}</Select></FormControl>}
 {node.type==='fill_null'&&<><ColumnSelect value={c.column} columns={columns} onChange={v=>set('column',v)}/><TextField size="small" label="Fill value" value={c.value||''} onChange={e=>set('value',e.target.value)}/></>}
 {node.type==='case'&&<><ColumnSelect value={c.column} columns={columns} onChange={v=>set('column',v)}/><FormControl size="small"><InputLabel>Case</InputLabel><Select label="Case" value={c.mode||'upper'} onChange={e=>set('mode',e.target.value)}><MenuItem value="upper">UPPER</MenuItem><MenuItem value="lower">lower</MenuItem><MenuItem value="title">Proper Case</MenuItem></Select></FormControl></>}
 {node.type==='top_n'&&<TextField size="small" type="number" label="Rows" value={c.count||100} onChange={e=>set('count',+e.target.value)}/>}
 {node.type==='calculated'&&<><TextField size="small" label="New column" value={c.name||''} onChange={e=>set('name',e.target.value)}/><TextField multiline rows={4} label="Expression" placeholder="price * quantity" value={c.expression||''} onChange={e=>set('expression',e.target.value)}/><Typography variant="caption" color="text.secondary">Use column names, arithmetic, and Pandas query expressions.</Typography></>}
 {node.type==='input'&&<Alert severity="info">{c.originalName}<br/>{c.size?`${(c.size/1024).toFixed(1)} KB`:''}</Alert>}
 </Stack></Box>
}
function ColumnSelect({value,columns,onChange}:{value:string;columns:string[];onChange:(v:string)=>void}){return <FormControl size="small"><InputLabel>Column</InputLabel><Select label="Column" value={value||''} onChange={e=>onChange(e.target.value)}>{columns.map(x=><MenuItem value={x}>{x}</MenuItem>)}</Select></FormControl>}

function PreviewTable({data}:{data?:Preview}){
 const [tab,setTab]=useState(0);if(!data)return <Box className="previewBlank"><TableChart/><Typography>Run the pipeline to preview data at every step</Typography></Box>
 return <Box><Stack direction="row" alignItems="center" px={2}><Tabs value={tab} onChange={(_,v)=>setTab(v)}><Tab label="Data"/><Tab label={`Columns (${data.columnCount})`}/><Tab label={`Errors (${data.errors?.length||0})`}/></Tabs><Box flex={1}/><Chip label={`${data.rowCount.toLocaleString()} rows`} size="small"/><Chip label={`${data.duplicateCount} duplicates`} size="small" sx={{ml:1}}/></Stack><Box className="tableWrap">{tab===0?<table><thead><tr><th>#</th>{data.columns.map(c=><th>{c.name}<small>{c.type}</small></th>)}</tr></thead><tbody>{data.rows.slice(0,30).map((r,i)=><tr><td>{i+1}</td>{data.columns.map(c=><td className={r[c.name]==null?'null':''}>{r[c.name]==null?'NULL':String(r[c.name])}</td>)}</tr>)}</tbody></table>:tab===1?<table><thead><tr><th>Column</th><th>Type</th><th>Null</th><th>Distinct</th></tr></thead><tbody>{data.columns.map(c=><tr><td>{c.name}</td><td>{c.type}</td><td>{c.nullCount} ({c.nullPercent}%)</td><td>{c.distinctCount}</td></tr>)}</tbody></table>:<Box p={2}>{data.errors?.length?data.errors.map((e:any)=><Alert severity="error" sx={{mb:1}}>Row {e.row} · {e.column}: {e.reason}</Alert>):<Alert severity="success">No validation errors</Alert>}</Box>}</Box></Box>
}

function Designer(){
 const {id}=useParams(),nav=useNavigate(),[p,setP]=useState<Pipeline>(),[selected,setSelected]=useState<string>(),[run,setRun]=useState<Execution>(),[busy,setBusy]=useState(false),[snack,setSnack]=useState(''),[library,setLibrary]=useState(true),sensors=useSensors(useSensor(PointerSensor))
 useEffect(()=>{api.get<Pipeline>(`/pipelines/${id}`).then(r=>setP(r.data))},[id])
 const selectedNode=p?.nodes.find(n=>n.id===selected), result=run?.node_results.find(n=>n.nodeId===selected)||run?.node_results.at(-1), columns=result?.columns.map(c=>c.name)||p?.nodes.find(n=>n.type==='input')?.config.preview?.columns?.map((c:any)=>c.name)||[]
 nodeRunResults.clear();run?.node_results.forEach(result=>nodeRunResults.set(result.nodeId,{status:result.status,error:result.error}))
 if(!p)return <Box className="center"><CircularProgress/></Box>
 const changeNodes=(nodes:PipelineNode[])=>setP({...p,nodes})
 const add=(type:NodeType)=>{const node:PipelineNode={id:crypto.randomUUID(),type,name:labels[type],config:type==='top_n'?{count:100}:type==='validation'?{rule:'null'}:{}};changeNodes([...p.nodes,node]);setSelected(node.id)}
 const upload=async(e:any)=>{const files=[...e.target.files] as File[];for(const file of files){const form=new FormData();form.append('file',file);const {data}=await api.post('/uploads',form);const node:PipelineNode={id:crypto.randomUUID(),type:'input',name:file.name.replace(/\.[^.]+$/,''),config:data};changeNodes([...p.nodes,node])}}
 const save=async()=>{setP(await savePipeline(p));setSnack('Pipeline saved')}
 const execute=async()=>{await save();setBusy(true);const r=await runPipeline(p.id);setRun(r);setBusy(false);setSnack(r.status==='success'?'Pipeline completed':'Pipeline failed')}
 const executeSelected=async()=>{
  if(!selected)return
  await save();setBusy(true)
  const r=await runToNode(p.id,selected)
  setRun(r);setBusy(false);setSnack(r.status==='success'?`Completed through ${selectedNode?.name}`:'Selected step failed')
 }
 const exportPipeline=()=>{
  const payload={format:'dataflow-studio',formatVersion:1,exportedAt:new Date().toISOString(),pipeline:{name:p.name,description:p.description,created_by:p.created_by,tags:p.tags,nodes:p.nodes,connections:p.connections}}
  const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'})
  const url=URL.createObjectURL(blob),link=document.createElement('a')
  link.href=url;link.download=`${p.name.replace(/[^a-z0-9-_]+/gi,'-').toLowerCase()||'pipeline'}.json`;link.click()
  URL.revokeObjectURL(url);setSnack('Pipeline exported')
 }
 const drag=(e:DragEndEvent)=>{if(e.over&&e.active.id!==e.over.id){const a=p.nodes.findIndex(n=>n.id===e.active.id),b=p.nodes.findIndex(n=>n.id===e.over!.id);changeNodes(arrayMove(p.nodes,a,b))}}
 return <Box className="designer"><Box className="designerBar"><IconButton onClick={()=>nav('/')}><ArrowBack/></IconButton><Box><TextField variant="standard" value={p.name} onChange={e=>setP({...p,name:e.target.value})} InputProps={{disableUnderline:true,sx:{fontWeight:800,fontSize:18}}}/><Typography variant="caption" color="text.secondary">v{p.version} · Autosaved locally</Typography></Box><Box flex={1}/><Button startIcon={<FileDownload/>} onClick={exportPipeline}>Export</Button><Button startIcon={<Save/>} onClick={save}>Save</Button><Button variant="outlined" startIcon={<PlayArrow/>} disabled={busy||!selected} onClick={executeSelected}>Run selected</Button><Button variant="contained" startIcon={busy?<CircularProgress size={17} color="inherit"/>:<PlayArrow/>} disabled={busy||!p.nodes.length} onClick={execute}>Run pipeline</Button></Box>
 <Box className="workbench"><aside className={`library ${library?'':'collapsed'}`}><Stack direction="row" alignItems="center" p={2}><Typography fontWeight={800} flex={1}>Node library</Typography><IconButton size="small" onClick={()=>setLibrary(false)}>‹</IconButton></Stack><Box px={2}><Button component="label" fullWidth variant="outlined" startIcon={<CloudUpload/>}>Add input files<input hidden multiple type="file" accept=".csv,.tsv,.xlsx,.parquet" onChange={upload}/></Button></Box><Box className="libraryScroll">{catalog.map(group=><Box key={group.category} p={2}><Typography variant="overline" color="text.secondary">{group.category}</Typography>{group.items.map(item=><Button key={item.type} className="libraryItem" onClick={()=>add(item.type)}><span>{item.icon}</span>{item.label}<Add fontSize="small"/></Button>)}</Box>)}</Box></aside>
 <main className="canvas">{!library&&<IconButton className="openLibrary" onClick={()=>setLibrary(true)}>›</IconButton>}<Box className="canvasHead"><Box><Typography variant="h6" fontWeight={800}>Pipeline flow</Typography><Typography variant="body2" color="text.secondary">Drag steps to reorder · select to configure</Typography></Box><Chip label={`${p.nodes.length} steps`} /></Box><DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={drag}><SortableContext items={p.nodes} strategy={verticalListSortingStrategy}><Box className="flow">{p.nodes.length===0?<Box className="dropzone"><CloudUpload/><Typography variant="h6">Start with an input file</Typography><Typography color="text.secondary">Upload CSV, TSV, Excel, or Parquet</Typography></Box>:p.nodes.map((n,i)=><SortableNode key={n.id} node={n} index={i+1} selected={selected===n.id} onSelect={()=>setSelected(n.id)}/>)}</Box></SortableContext></DndContext></main>
 <aside className="properties"><Properties node={selectedNode} columns={columns} onChange={n=>changeNodes(p.nodes.map(x=>x.id===n.id?n:x))} onDelete={()=>{changeNodes(p.nodes.filter(x=>x.id!==selected));setSelected(undefined)}}/></aside></Box>
 <section className="preview"><Box className="previewTitle"><Typography fontWeight={800}>Output preview</Typography>{run&&<><Chip color={run.status==='success'?'success':'error'} label={run.status}/><Typography variant="caption">{run.duration_ms}ms · {run.output_rows.toLocaleString()} rows · {run.validation_errors} errors</Typography></>}</Box><PreviewTable data={result}/></section><Snackbar open={!!snack} autoHideDuration={2500} onClose={()=>setSnack('')} message={snack}/></Box>
}

export default function App(){const [dark,setDark]=useState(localStorage.theme==='dark');useEffect(()=>{localStorage.theme=dark?'dark':'light'},[dark]);const theme=useMemo(()=>createTheme({palette:{mode:dark?'dark':'light',primary:{main:'#6d5dfc'},background:{default:dark?'#11131a':'#f6f7fb',paper:dark?'#191c25':'#fff'}},shape:{borderRadius:12},typography:{fontFamily:'Inter, system-ui, sans-serif'},components:{MuiButton:{defaultProps:{disableElevation:true},styleOverrides:{root:{textTransform:'none',fontWeight:700,borderRadius:9}}}}}),[dark]);return <ThemeProvider theme={theme}><CssBaseline/><Routes><Route path="/" element={<Shell dark={dark} setDark={setDark}><Dashboard/></Shell>}/><Route path="/pipeline/:id" element={<Designer/>}/></Routes></ThemeProvider>}
